### PR TITLE
repo/path wildcard matching - closes #151

### LINKED ISSUE #151: Support owner and path wildcards in repoPaths
**Is your feature request related to a problem? Please describe.**
Individually defining repositories and related paths for many repos and orgs requires maintenance of config settings

**Describe the solution you'd like**
Support resolving `owner/*` in config to use a wildcard partial path and substitute `repo` name as end of path.
Support overriding a full owner/repo match to a fully-qualified path, even if a wildcard match is available.

### PR DESCRIPTION
**Pull request by cdxn**
# Summary
Adds support for use of repository and path wildcards in `config:repoPaths` to permit:

- owner/* repo matching to common local path (path-segment/*)
- match `owner/*` to `path-segment/repo`
- prioritize full repo ( `owner/repo: ~/somePath/target`) when present
- executes only when invoking `runCustomCommand`

Avoids having to individually add each repo-path combination for org/owner while retaining no-match/no-mapping behavior and prioritizing direct-mapped owner/repo to full path.

Assumes repo wildcard match is defined as `owner/*` and that path is well-formed partial path, ending with `/*`

First `go` attempt - chose simple `strings` manipulation over `regexp` given the limited matching cases of owner/repo, owner/\*, path/.../\*. Also chose to introduce `getRepoLocalPath` in modelUtils.go as a direct function vs. a type method, since it didn't appear elsewhere or make sense to be "generally useful from the Model"

Happy to revise or adjust approach.

## How did you test this change?
- Mapped custom command to cd to RepoPath, launch vs code, checkout PrNumber
- Added config:repoPaths entries
- Have been using it locally with many org repos to fix and refactor

```yaml
repoPaths:
    owner/specific-repo: ~/code/specific-repo
    owner/*: ~/dev/owner/*
```

Incorrectly mapped paths, non-existent paths, repoPaths lookup misses retain error path when customCommand fails.

## Images/Videos

closes #151

### CODE REVIEW

**Comment by dlvhdr** [comment]
Thanks for the PR, looks awesome!
I'm gonna review it later this evening

**Review by dlvhdr — COMMENTED** [review]
Looks good @cdxn!
Can you please also add an example of this to the readme?
There's a section about the repo paths.

**Comment by cdxn** [comment]
good call - added within keybindings as sub-section - feel free to move/combine if you think it fits better elsewhere. I always forget the readme :D

**Comment by dlvhdr** [comment]
Awesome, thanks!

**Review by dlvhdr — APPROVED** [review]

**Pull request merged**
