### PR TITLE
feat: Add support for raspberry PI with ARM

### PR DESCRIPTION
**Pull request by Cian911**
# Summary

Enable `gh-dash` to run on a raspberry PI with support for ARM builds.

## How did you test this change?
Confirmed working on my raspberry PI

## Images/Videos

Image

### CODE REVIEW

**Comment by Cian911** [comment]
@dlvhdr would love your review whenever you get a chance ;)

**Review by dlvhdr — APPROVED** [review]
Thanks for this :) Are you running it on an external monitor or something? Would love a picture

**Comment by Cian911** [comment]
@dlvhdr No worries at all - looks like the CI has passed now so just needs to be merged, and I'm happy to oblige, here's a better one! 

Image

**Comment by dlvhdr** [comment]
Cool :) I'll add it in the upcoming minor release

**Pull request merged**
