### PR TITLE
(GH-260) Initial docs work

### LINKED ISSUE #260: Add Docs Site
**Is your feature request related to a problem? Please describe.**

When I want to show my coworkers how to use dash, I have to send them to the README, which is written for people who are already comfortable writing YAML configurations and willing to work through things on their own.

**Describe the solution you'd like**

I'd like to be able to point my coworkers and the people who get interested in this tool to a small docs site that has some narrative documentation for using the tool as well as reference documentation for
the configuration options.

**Describe alternatives you've considered**

Instead of a docs site, we could maintain a folder of Markdown documents in the repository.

**Additional context**

My day-job is documentation. I'd be happy to draft some initial documentation and help out with it in the long run.

### PR DESCRIPTION
**Pull request by michaeltlombardi**
This change adds a first draft of a docs site for `gh-dash` using Hugo. It includes:

- Install instructions
- Full CLI usage information
- Enumerated information for the builtin keybinding commands
- Full coverage of the configuration, including schematization and docs
- Instructions for how to get hover-help, IntelliSense, and validation for configurations in VS Code.
- A unified UI that displays UI icon elements in the docs the same as in the terminal
- Examples
- The contribution guide, minimally ported

There is a lot this does not address:

- This was high-touch work to get the schemas generated and available
- There is no "live edit" for configurations so users can select options
- This does not add CI or deployment - that needs to be worked out (Netlify or GitHub Pages, likely)
- This does not have a changelog on the site
- This does not have additional gifs of usage
- This does not have a versioning scheme for the configuration
- This does not have a custom favicon for the site

But it *is* a first draft and something we can start from, look to port to another toolset, or investigate improved maintainability for the schemas in the future - maybe with `go generate` or similar.

> **Note**
> The entire addition is colocated in `/docs`. We could split out everything but the content into `/site` and reference the docs from there, which might be cleaner/less burdensome to docs contributors. The schemas are defined in `/docs/data/schemas` and use some custom properties that the site uses for documentation but throws away when publishing the schema.
>
> You can test this change with `gh pr checkout 260 && cd docs && hugo serve`.

- Resolves #260

### CODE REVIEW

**Comment by dlvhdr** [comment]
This is great! You've done so much!

**Review by dlvhdr — DISMISSED** [review]

**Comment by michaeltlombardi** [comment]
@dlvhdr I just made a couple minor corrections, so I'm happy enough with merging it as-is, we can always iterate on it as we go! Once you get it up I can add some GitHub Actions for keeping the Hugo modules up-to-date and I'll always be happy to tag in on docs reviews or whatever going forward. I super appreciate you taking this contribution on board!

Once there's docs up I'll feel a lot more confident in trying to get coworkers using it, since they're primarily writers and developers. 😊

**Comment by dlvhdr** [comment]
Of course I'm happy to get this contribution, it's amazing :D
And yeah, there's no reason on polishing to perfection now, let's get it going!

**Comment by dlvhdr** [comment]
@michaeltlombardi hi :) I'm trying to deploy the docs site to github pages but the action fails with this error:

```
hugo --minify --gc --baseURL https://dlvhdr.github.io/gh-dash
Start building sites …
hugo v0.111.3+extended darwin/amd64 BuildDate=unknown
Error: Error building site: failed to render shortcode: "/Users/dolevh/code/personal/gh-dash/docs/content/configuration/keybindings/issues.md:14:1": failed to render shortcode "schematize": failed to process shortcode: "/var/folders/nz/4t7_fbbs781fgljt4p7k5fdm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/platenio/platen/modules/schematize@v0.0.0-20230504053552-c70b34ba1161/layouts/shortcodes/schematize.html:40:7": execute of template failed: template: shortcodes/schematize.html:40:7: executing "shortcodes/schematize.html" at <partial "schematize/docs/array" (dict "property" $property "page" $Page)>: error calling partial: execute of template failed: template: partials/schematize/docs/array.html:30:32: executing "partials/schematize/docs/array.html" at <partial "schematize/utils/metadata/render" $params>: error calling partial: "/var/folders/nz/4t7_fbbs781fgljt4p7k5fdm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/platenio/platen/modules/schematize@v0.0.0-20230504053552-c70b34ba1161/layouts/partials/schematize/utils/metadata/render.html:27:26": execute of template failed: template: partials/schematize/utils/metadata/render.html:27:26: executing "partials/schematize/utils/metadata/render.html" at <partial "schematize/utils/metadata/munge" $params>: error calling partial: "/var/folders/nz/4t7_fbbs781fgljt4p7k5fdm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/platenio/platen/modules/schematize@v0.0.0-20230504053552-c70b34ba1161/layouts/partials/schematize/utils/metadata/munge.html:181:19": execute of template failed: template: partials/schematize/utils/metadata/munge.html:181:19: executing "partials/schematize/utils/metadata/munge.html" at <partial "schematize/utils/metadata/munge" $recursiveParameters>: error calling partial: "/var/folders/nz/4t7_fbbs781fgljt4p7k5fdm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/platenio/platen/modules/schematize@v0.0.0-20230504053552-c70b34ba1161/layouts/partials/schematize/utils/metadata/munge.html:130:18": execute of template failed: template: partials/schematize/utils/metadata/munge.html:130:18: executing "partials/schematize/utils/metadata/munge.html" at <partial "schematize/utils/references/resolve/data" $params>: error calling partial: "/var/folders/nz/4t7_fbbs781fgljt4p7k5fdm0000gn/T/hugo_cache/modules/filecache/modules/pkg/mod/github.com/platenio/platen/modules/schematize@v0.0.0-20230504053552-c70b34ba1161/layouts/partials/schematize/utils/references/resolve/data.html:48:17": execute of template failed: template: partials/schematize/utils/references/resolve/data.html:48:17: executing "partials/schematize/utils/references/resolve/data.html" at <index $refData $refPath>: error calling index: index of type map[string]interface {} with args [<nil>] failed: value is nil; should be of type string
```

This works if I run hugo with a baseURL of `hugo --minify --gc --baseURL https://dlvhdr.github.io/` but the official hugo Github Action says to pass in a base url of `--baseURL "${{ steps.pages.outputs.base_url }}/"`.

**Pull request merged**
