### PR TITLE
feat(keys): implements first/last line navigation

### LINKED ISSUE #104: Keybind to go to the top or bottom (`g` and `G`)
**Is your feature request related to a problem? Please describe.**
A quality of life enhancement would be to let users navigate with more vim commands such as `gg` and `G`.

**Describe alternatives you've considered**
I will investigate if I can do this myself. I'm not sure if my Go knowledge is enough for this.

### PR DESCRIPTION
**Pull request by paulo-e**
Fixes #104.

I tested this issue by thinking about corner cases and trying them out.

Please ignore the weird quality

### CODE REVIEW

**Comment by dlvhdr** [comment]
Thanks @paulo-e!
I would like to solve navigation in a more consistent way though.
I need to think about a way to shift focus between the table and the sidebar.
Then `gg` and `G` will control the focused area. I think that's how most TUIs do it, but not sure.
Anyway, I think it should be `gg` and not `g`, but I'm not sure how to do it in `bubbletea`. Perhaps with saving the time between `g` presses and checking it's under 150ms or something.

**Comment by paulo-e** [comment]
I saw some other apps trying to emulate `gg` as `g` so that's why I did it. I think that if you are going to the sticky keys route, it should be done in a more generic way than just to use it here. 

About the table and sidebar, isn't the best way to use `tab` and `shift+tab`?

**Review by pangsirirat422 — APPROVED** [review]

**Review by pangsirirat422 — APPROVED** [review]

**Review by pangsirirat422 — APPROVED** [review]

**Review by Churru14 — APPROVED** [review]

**Review by pangsirirat422 — APPROVED** [review]

**Review by pangsirirat422 — APPROVED** [review]

**Review by pangsirirat422 — APPROVED** [review]

**Review by ndom91 — APPROVED** [review]
LGTM :+1:

**Review by dlvhdr — APPROVED** [review]
Hey @paulo-e, I think I'm good with this now, as I've created a way to override keybindings in #126 .
Do you want to merge this?

**Pull request merged**
