### PR TITLE
Remove truncation of repo name.

### PR DESCRIPTION
**Pull request by robdimsdale**
# Summary

Removes truncation on repo name and adds full name + number to the sidebar. See #217 .

## How did you test this change?

Manually, with a repo name longer than the default of 18 characters.

### CODE REVIEW

**Comment by dlvhdr** [comment]
Looks good! Can you please provide a screenshot of how the sidebar looks with this change?

**Comment by robdimsdale** [comment]
Sure - here's an example:

Screen Shot 2023-01-18 at 2 31 31 PM

**Comment by robdimsdale** [comment]
Pushed a commit with that change. Here's a screenshot:

Screen Shot 2023-01-19 at 8 29 24 AM

**Comment by robdimsdale** [comment]
Addressing [this question](https://github.com/dlvhdr/gh-dash/issues/217#issuecomment-1387621541) here:

> Cool, so without grow=true, how does that look? Can you add a screenshot?

The screenshots above actually do not have `grow=true` - I just increased the column width in the config.

Here is a smaller (default) column width - smaller than a repo name:

Screen Shot 2023-01-19 at 8 44 33 AM

And here is the same data with a manually-increased column width:

Screen Shot 2023-01-19 at 8 45 12 AM

**Comment by dlvhdr** [comment]
Awesome, looks good!

**Pull request merged**
